In [11]:
import numpy as np
import torch
from torch import Tensor
from torch import nn

In [16]:
# moduledict
moduledict1 = nn.ModuleDict({'cond2d': nn.Conv2d(10,10,3)})
moduledict2 = nn.ModuleDict({'relu': nn.ReLU(), 'dict1': moduledict1})
print(moduledict1)
print(moduledict2)

ModuleDict(
  (cond2d): Conv2d(10, 10, kernel_size=(3, 3), stride=(1, 1))
)
ModuleDict(
  (relu): ReLU()
  (dict1): ModuleDict(
    (cond2d): Conv2d(10, 10, kernel_size=(3, 3), stride=(1, 1))
  )
)


In [20]:
# ReLU
input = torch.randn(10)
output = nn.ReLU()(input)
print(output)

tensor([1.6873, 1.1444, 0.3280, 0.0000, 0.2289, 0.2976, 0.0000, 0.4835, 1.1768,
        2.1066])


In [23]:
# Linear
input = torch.randn(128, 20)
output = nn.Linear(20,30)(input)
print(output.size())

torch.Size([128, 30])


In [25]:
# BCELoss
m = nn.Sigmoid()
input = torch.randn(3, 2, requires_grad=True)
target = torch.rand(3, 2, requires_grad=False)
output = nn.BCELoss()(m(input), target)
print(output)

tensor(0.7983, grad_fn=<BinaryCrossEntropyBackward0>)


In [31]:
input = torch.arange(1, 5, dtype=torch.float32).view(1, 1, 2, 2)
print(input)

m = nn.Upsample(scale_factor=2, mode='nearest')
print(m(input))

m = nn.Upsample(scale_factor=2, mode='bilinear')  # align_corners=False
print(m(input))

m = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
print(m(input))

# # Try scaling the same data in a larger tensor
# input_3x3 = torch.zeros(3, 3).view(1, 1, 3, 3)
# input_3x3[:, :, :2, :2].copy_(input)
# input_3x3

# m = nn.Upsample(scale_factor=2, mode='bilinear')  # align_corners=False
# # Notice that values in top left corner are the same with the small input (except at boundary)
# m(input_3x3)

# m = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
# # Notice that values in top left corner are now changed
# m(input_3x3)

tensor([[[[1., 2.],
          [3., 4.]]]])
tensor([[[[1., 1., 2., 2.],
          [1., 1., 2., 2.],
          [3., 3., 4., 4.],
          [3., 3., 4., 4.]]]])
tensor([[[[1.0000, 1.2500, 1.7500, 2.0000],
          [1.5000, 1.7500, 2.2500, 2.5000],
          [2.5000, 2.7500, 3.2500, 3.5000],
          [3.0000, 3.2500, 3.7500, 4.0000]]]])
tensor([[[[1.0000, 1.3333, 1.6667, 2.0000],
          [1.6667, 2.0000, 2.3333, 2.6667],
          [2.3333, 2.6667, 3.0000, 3.3333],
          [3.0000, 3.3333, 3.6667, 4.0000]]]])


In [33]:
m = nn.Identity(54, unused_argument1=0.1, unused_argument2=False)
input = torch.randn(128, 20)
output = nn.Identity(54, unused_argument1=0.1, unused_argument2=False)(input)
print(output.size())

torch.Size([128, 20])


In [39]:
multihead_attn = nn.MultiheadAttention(32, 8)
query = torch.randn(2, 1, 32)
key = torch.randn(2, 1, 32)
value = torch.randn(2, 1, 32)
attn_output, attn_output_weights = multihead_attn(query, key, value)
print(attn_output)

tensor([[[-0.0402,  0.0576,  0.2065, -0.1296,  0.1422, -0.0145, -0.5225,
          -0.3057,  0.1891,  0.5322, -0.0604,  0.0228, -0.0846, -0.5631,
           0.1770,  0.2748, -0.0023,  0.2098,  0.0771,  0.2433, -0.0380,
           0.1194,  0.0113,  0.4350, -0.0378, -0.0177,  0.0755,  0.1787,
           0.2030, -0.0697,  0.2827, -0.6169]],

        [[ 0.0134, -0.0031,  0.2839, -0.1390,  0.2343,  0.0092, -0.6052,
          -0.1563,  0.1205,  0.5575, -0.0382,  0.0488, -0.1163, -0.5516,
           0.1896,  0.2201,  0.0050,  0.2661, -0.0560,  0.0487,  0.0055,
          -0.0456, -0.0158,  0.5236, -0.0962, -0.0434,  0.0006,  0.2224,
           0.1588, -0.1222,  0.3569, -0.5909]]], grad_fn=<ViewBackward0>)


In [42]:
transformer_model = nn.Transformer(nhead=16, num_encoder_layers=12)
src = torch.rand((10, 32, 512))
tgt = torch.rand((20, 32, 512))
out = transformer_model(src, tgt)
print(out.size())

torch.Size([20, 32, 512])
