In [12]:
import numpy as np
import torch
from torch import Tensor
from torch import nn
import time

In [13]:
start = time.time()
# an Embedding module containing 10 tensors of size 3
embedding = nn.Embedding(10, 3)
# a batch of 2 samples of 4 indices each
input = torch.LongTensor([[1, 2, 4, 5], [4, 3, 2, 9]])
print(embedding(input))

# example with padding_idx
embedding = nn.Embedding(10, 3, padding_idx=0)
input = torch.LongTensor([[0, 2, 4, 5], [3, 3, 2, 9]])
print(embedding(input))
end = time.time()
print(end-start)

# # example of changing `pad` vector
# padding_idx = 0
# embedding = nn.Embedding(3, 3, padding_idx=padding_idx)
# print(embedding.weight)
# with torch.no_grad():
#     embedding.weight[padding_idx] = torch.ones(3)
# print(embedding.weight)

tensor([[[ 1.1268, -0.9513,  0.6823],
         [-0.3245, -0.8497, -0.7579],
         [-0.6075,  2.7415, -2.0689],
         [-1.4612, -1.0289, -0.4242]],

        [[-0.6075,  2.7415, -2.0689],
         [ 2.1071,  0.1938,  0.0255],
         [-0.3245, -0.8497, -0.7579],
         [-0.4831, -1.7133,  0.5985]]], grad_fn=<EmbeddingBackward0>)
tensor([[[ 0.0000,  0.0000,  0.0000],
         [-1.0849,  1.1815,  1.0977],
         [ 0.9290,  1.8014, -0.3725],
         [ 0.0787,  1.9454,  1.1112]],

        [[ 1.7580, -0.3959,  0.9574],
         [ 1.7580, -0.3959,  0.9574],
         [-1.0849,  1.1815,  1.0977],
         [ 0.3496,  1.7060, -0.4346]]], grad_fn=<EmbeddingBackward0>)
0.004005908966064453


In [15]:
import mindspore as ms
from mindspore import nn
from mindspore import Tensor

start = time.time()
embedding = nn.Embedding(10, 3)
# a batch of 2 samples of 4 indices each
input = Tensor([[1, 2, 4, 5], [4, 3, 2, 9]])
print(embedding(input))

# example with padding_idx
embedding = nn.Embedding(10, 3, padding_idx=0)
input = Tensor([[0, 2, 4, 5], [3, 3, 2, 9]])
print(embedding(input))
end = time.time()
print(end-start)

[[[-0.0065871   0.01535338  0.01434076]
  [ 0.00331824  0.00791553 -0.02024699]
  [ 0.01239492  0.00385856  0.00478753]
  [-0.01227701  0.00011452  0.0142579 ]]

 [[ 0.01239492  0.00385856  0.00478753]
  [-0.00323425  0.00501913 -0.00874054]
  [ 0.00331824  0.00791553 -0.02024699]
  [ 0.01642694 -0.0065531   0.00681009]]]
[[[ 0.          0.          0.        ]
  [ 0.00261477  0.01124485  0.00828796]
  [-0.00046545  0.00450285  0.00737254]
  [-0.01147073  0.00254146  0.00321731]]

 [[-0.00656487 -0.00497597 -0.00669393]
  [-0.00656487 -0.00497597 -0.00669393]
  [ 0.00261477  0.01124485  0.00828796]
  [ 0.00989333  0.02307425  0.01142865]]]
0.00896143913269043


**MindSpore Embedding用法与输出与PyTorch一致**
- mint.nn.embedding待验证，CPU不支持