In [1]:
import numpy as np
import torch
from torch import Tensor
from torch import nn

In [4]:
# input = torch.arange(1, 5, dtype=torch.float32).view(1, 1, 2, 2)
input = np.random.randint(2, size=(1,1,2,2))
print(input)

m = nn.Upsample(scale_factor=2, mode='nearest')
print(m(Tensor(input)))

m = nn.Upsample(scale_factor=2, mode='bilinear')  # align_corners=False
print(m(Tensor(input)))

m = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
print(m(Tensor(input)))

# # Try scaling the same data in a larger tensor
# input_3x3 = torch.zeros(3, 3).view(1, 1, 3, 3)
# input_3x3[:, :, :2, :2].copy_(input)
# input_3x3

# m = nn.Upsample(scale_factor=2, mode='bilinear')  # align_corners=False
# # Notice that values in top left corner are the same with the small input (except at boundary)
# m(input_3x3)

# m = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
# # Notice that values in top left corner are now changed
# m(input_3x3)

[[[[1 1]
   [1 0]]]]
tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 0., 0.],
          [1., 1., 0., 0.]]]])
tensor([[[[1.0000, 1.0000, 1.0000, 1.0000],
          [1.0000, 0.9375, 0.8125, 0.7500],
          [1.0000, 0.8125, 0.4375, 0.2500],
          [1.0000, 0.7500, 0.2500, 0.0000]]]])
tensor([[[[1.0000, 1.0000, 1.0000, 1.0000],
          [1.0000, 0.8889, 0.7778, 0.6667],
          [1.0000, 0.7778, 0.5556, 0.3333],
          [1.0000, 0.6667, 0.3333, 0.0000]]]])


In [6]:
import mindspore as ms
from mindspore import nn
from mindspore import Tensor

m = nn.Upsample(scale_factor=2.0, mode='nearest')
print(m(Tensor(input)))

m = nn.Upsample(scale_factor=2.0, mode='bilinear')  # align_corners=False
print(m(Tensor(input)))

m = nn.Upsample(scale_factor=2.0, mode='bilinear', align_corners=True)
print(m(Tensor(input)))

ValueError: For 'interpolate', 'scale_factor' option cannot currently be set with the mode = nearest and dim = 4D.

- jax没有upsample接口
- MindSpore的scale_factor参数必须为float
- MindSpore部分输入不支持